jobs:

# jobs for this shippableSamples demo 

################################

# runCI job that builds and pushes artifact to Amazon ECR
  - name: e2eShippableDemo_runCI
    type: runCI
    flags:
      - e2eShippableDemo
    steps:
      - OUT: e2eshipdemo-img-ecs
  
# generate manifest
  - name: e2eshipdemo-manifest-ecs
    type: manifest
    flags:
      - e2eShippableDemo
    steps:
      - IN: e2eshipdemo-img-ecs
      - IN: e2eshipdemo-img-options-ecs-test
      - TASK: managed

# Create TEST Release
  - name: e2eshipdemo-release-ecs-beta
    type: release
    flags:
      - e2eShippableDemo
    steps:
      - IN: e2eshipdemo-manifest-ecs
      - IN: e2eshipdemo-version-ecs
      - TASK: managed
        bump: beta

# TEST deployment to Amazon ECS
  - name: e2eshipdemo-deploy-ecs-test
    type: deploy
    flags:
      - e2eShippableDemo
    steps:
      - IN: e2eshipdemo-release-ecs-beta
      - IN: e2eshipdemo-params-ecs-test
      - IN: e2eshipdemo-cluster-ecs
      - IN: e2eshipdemo-alb-test
        applyTo:
          - manifest: e2eshipdemo-manifest-ecs
            image: e2eshipdemo-img-ecs
            port: 80
      - TASK: managed

# Create PROD Release
  - name: e2eshipdemo-release-ecs-prod
    type: release
    flags:
      - e2eShippableDemo
    steps:
      - IN: e2eshipdemo-deploy-ecs-test
        switch: off
      # - IN: e2eshipdemo-version-ecs
      - TASK: managed
        bump: final

# PROD deployment to Amazon ECS
  - name: e2eshipdemo-deploy-ecs-prod
    type: deploy
    flags:
      - e2eShippableDemo
    steps:
      # - IN: e2eshipdemo-deploy-ecs-test
      #   switch: off
      - IN: e2eshipdemo-release-ecs-prod
        switch: off
      - IN: e2eshipdemo-params-ecs-prod
      - IN: e2eshipdemo-img-options-ecs-prod
      - IN: e2eshipdemo-replicas-ecs-prod
      - IN: e2eshipdemo-cluster-ecs
      - IN: e2eshipdemo-alb-prod
        applyTo:
          - manifest: e2eshipdemo-manifest-ecs
            image: e2eshipdemo-img-ecs
            port: 80
      - TASK: managed
