jobs:

########################## INFRA AUTOMATION JOBS #########################
# job to setup AWS IAM roles, profiles etc.
 - name: aws_infra_setup
   type: runCLI
   steps:
     - IN: aws_pem
     - IN: build_ami
       switch: off
     - IN: aws_creds
     - IN: auto_repo
       switch: off
     - TASK:
       - script: sudo apt-get install -y jq
       - script: IN/auto_repo/gitRepo/infra/provisionAWS.sh awsSetupIAM
   on_success:
     - script: echo "SUCCESS"
   on_failure:
     - script: echo "FAILURE"
   always:
     - script: /build/IN/auto_repo/gitRepo/infra/archiveProvisionState.sh awsSetupIAM

# job to create AWS AMI used to deploy VMs
 - name: build_ami
   type: runCLI
   steps:
     - IN: aws_creds
     - IN: auto_repo
       switch: off
     - IN: bldami_params
     - TASK:
       - script: sudo apt-get install -y jq
       - script: IN/auto_repo/gitRepo/infra/awsBuildAMI/basePack.sh bldami_params
   on_success:
     - script: echo "SUCCESS"
   on_failure:
     - script: cat /build/IN/auto_repo/gitRepo/infra/awsBuildAMI/output.txt

# job to provision TEST VMs and ECS cluster
 - name: test_infra_prov
   type: runCLI
   steps:
     - IN: aws_pem
     - IN: aws_creds
     - IN: auto_repo
       switch: off
     - IN: build_ami
       switch: off
     - IN: aws_infra_setup
     - TASK:
       - script: sudo apt-get install -y jq
       - script: IN/auto_repo/gitRepo/infra/provisionAWS.sh awsTestECS
   on_success:
     - script: echo "SUCCESS"
   on_failure:
     - script: echo "FAILURE"
   always:
     - script: /build/IN/auto_repo/gitRepo/infra/archiveProvisionState.sh awsTestECS

# job to provision PROD VMs and ECS cluster
 - name: prod_infra_prov
   type: runCLI
   steps:
     - IN: aws_pem
     - IN: aws_creds
     - IN: aws_infra_setup
     - IN: auto_repo
       switch: off
     - IN: build_ami
       switch: off
     - TASK:
       - script: sudo apt-get install -y jq
       - script: IN/auto_repo/gitRepo/infra/provisionAWS.sh awsProdECS
   on_success:
     - script: echo "SUCCESS"
   on_failure:
     - script: echo "FAILURE"
   always:
     - script: /build/IN/auto_repo/gitRepo/infra/archiveProvisionState.sh awsProdECS
